"""esquema inicial del backup

Revision ID: 8c123f819019
Revises: 
Create Date: 2026-09-01 17:51:01.667294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c123f819019'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_message_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("chat_type IN ('individual', 'group', 'broadcast', 'newsletter', 'unknown')", name='ck_chats_chat_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jid')
    )
    op.create_index('ix_chats_last_message_timestamp', 'chats', ['last_message_timestamp'], unique=False, postgresql_using='btree')
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jid', sa.String(length=128), nullable=False),
    sa.Column('lid', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('push_name', sa.Text(), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jid')
    )
    op.create_index('ix_contacts_lid', 'contacts', ['lid'], unique=False)
    op.create_index('ix_contacts_phone_number', 'contacts', ['phone_number'], unique=False)
    op.create_index('ix_contacts_push_name', 'contacts', ['push_name'], unique=False)
    op.create_table('chat_history_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_jid', sa.String(length=128), nullable=False),
    sa.Column('oldest_message_id', sa.String(length=128), nullable=True),
    sa.Column('oldest_message_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('newest_message_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('requests_sent', sa.Integer(), nullable=False),
    sa.Column('responses_received', sa.Integer(), nullable=False),
    sa.Column('history_status', sa.String(length=20), nullable=False),
    sa.Column('last_response_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_no_progress', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("history_status IN ('pending', 'fetching', 'exhausted', 'server_limited', 'timeout', 'error', 'no_valid_cursor')", name='ck_history_state_status'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('chat_jid')
    )
    op.create_index('ix_history_state_status', 'chat_history_state', ['history_status'], unique=False)
    op.create_table('history_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('protocol_request_id', sa.String(length=128), nullable=True),
    sa.Column('peer_data_request_session_id', sa.String(length=128), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_jid', sa.String(length=128), nullable=False),
    sa.Column('cursor_message_id', sa.String(length=128), nullable=True),
    sa.Column('cursor_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('sent', 'acked', 'received', 'timeout', 'error')", name='ck_history_requests_status'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_history_requests_chat_jid', 'history_requests', ['chat_jid'], unique=False)
    op.create_index('ix_history_requests_protocol_id', 'history_requests', ['protocol_request_id'], unique=False)
    op.create_index('ix_history_requests_status', 'history_requests', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_jid', sa.String(length=128), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=128), nullable=True),
    sa.Column('synthetic_identifier', sa.String(length=128), nullable=True),
    sa.Column('sender_jid', sa.String(length=128), nullable=True),
    sa.Column('sender_lid', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('from_me', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_proto', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('initial_history', 'on_demand', 'live', 'unknown')", name='ck_messages_source'),
    sa.CheckConstraint('whatsapp_message_id IS NULL OR length(whatsapp_message_id) > 0', name='ck_messages_wamid_not_empty'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_id_timestamp', 'messages', ['chat_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_chat_jid_timestamp', 'messages', ['chat_jid', 'timestamp'], unique=False)
    op.create_index('ix_messages_sender_jid', 'messages', ['sender_jid'], unique=False)
    op.create_index('ix_messages_source', 'messages', ['source'], unique=False)
    op.create_index('uq_messages_chat_wamid', 'messages', ['chat_jid', 'whatsapp_message_id'], unique=True, postgresql_where=sa.text('whatsapp_message_id IS NOT NULL'))
    op.create_table('media_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=128), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('direct_path', sa.Text(), nullable=True),
    sa.Column('media_key', sa.LargeBinary(), nullable=True),
    sa.Column('file_sha256', sa.LargeBinary(), nullable=True),
    sa.Column('file_enc_sha256', sa.LargeBinary(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=False),
    sa.Column('download_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("download_status IN ('pending', 'downloading', 'downloaded', 'unavailable', 'expired', 'failed')", name='ck_media_files_download_status'),
    sa.CheckConstraint("media_type IN ('image', 'video', 'gif', 'audio', 'voice_note', 'sticker', 'document', 'unknown')", name='ck_media_files_media_type'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'media_type', name='uq_media_files_message_type')
    )
    op.create_index('ix_media_files_chat_id', 'media_files', ['chat_id'], unique=False)
    op.create_index('ix_media_files_download_status', 'media_files', ['download_status'], unique=False)
    op.create_index('ix_media_files_file_sha256', 'media_files', ['file_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_files_file_sha256', table_name='media_files')
    op.drop_index('ix_media_files_download_status', table_name='media_files')
    op.drop_index('ix_media_files_chat_id', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('uq_messages_chat_wamid', table_name='messages', postgresql_where=sa.text('whatsapp_message_id IS NOT NULL'))
    op.drop_index('ix_messages_source', table_name='messages')
    op.drop_index('ix_messages_sender_jid', table_name='messages')
    op.drop_index('ix_messages_chat_jid_timestamp', table_name='messages')
    op.drop_index('ix_messages_chat_id_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_history_requests_status', table_name='history_requests')
    op.drop_index('ix_history_requests_protocol_id', table_name='history_requests')
    op.drop_index('ix_history_requests_chat_jid', table_name='history_requests')
    op.drop_table('history_requests')
    op.drop_index('ix_history_state_status', table_name='chat_history_state')
    op.drop_table('chat_history_state')
    op.drop_index('ix_contacts_push_name', table_name='contacts')
    op.drop_index('ix_contacts_phone_number', table_name='contacts')
    op.drop_index('ix_contacts_lid', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_chats_last_message_timestamp', table_name='chats', postgresql_using='btree')
    op.drop_table('chats')
    op.drop_table('app_state')
    # ### end Alembic commands ###
