"""cuentas, sesiones web y credenciales de google

Revision ID: e628c9f290d0
Revises: 142f4b5daff4
Create Date: 2026-09-03 12:28:39.437456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e628c9f290d0'
down_revision: Union[str, Sequence[str], None] = '142f4b5daff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # CITEXT para el correo: dos personas no pueden registrarse con
    # Ana@x.com y ana@x.com. Sin la extension, la tabla users ni se crea.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=16), nullable=False),
    sa.Column('google_subject', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("auth_provider IN ('local','google','both')", name='ck_users_auth_provider'),
    sa.CheckConstraint('password_hash IS NOT NULL OR google_subject IS NOT NULL', name='ck_users_tiene_alguna_credencial'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_subject')
    )
    op.create_table('google_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_subject', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('wa_pn', sa.String(length=64), nullable=True),
    sa.Column('wa_lid', sa.String(length=64), nullable=True),
    sa.Column('session_status', sa.String(length=20), nullable=False),
    sa.Column('session_storage_key', sa.String(length=128), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("session_status IN ('never_linked','linked','revoked','error')", name='ck_whatsapp_accounts_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_storage_key', name='uq_whatsapp_accounts_storage')
    )
    op.create_index('ix_whatsapp_accounts_user', 'whatsapp_accounts', ['user_id'], unique=False)
    op.add_column('chats', sa.Column('whatsapp_account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chats_whatsapp_account_id'), 'chats', ['whatsapp_account_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'whatsapp_accounts', ['whatsapp_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # La extension NO se elimina: puede haberla creado otra cosa, y quitarla
    # rompería cualquier otra columna que la use.

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_whatsapp_account_id'), table_name='chats')
    op.drop_column('chats', 'whatsapp_account_id')
    op.drop_index('ix_whatsapp_accounts_user', table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    op.drop_index('ix_user_sessions_user', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('google_credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
