"""huella del archivo local para comprobar la subida

Revision ID: effd3e8aa39f
Revises: c7c9f6d75957
Create Date: 2026-09-03 13:57:26.909714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effd3e8aa39f'
down_revision: Union[str, Sequence[str], None] = 'c7c9f6d75957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('plaintext_sha256', sa.String(length=64), nullable=True))
    op.alter_column('media_files', 'storage_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'storage_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'text_truncated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text_truncated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('messages', 'storage_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=False)
    op.alter_column('media_files', 'storage_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=False)
    op.drop_column('media_files', 'plaintext_sha256')
    # ### end Alembic commands ###
