"""intento de semilla por chat

Revision ID: 142f4b5daff4
Revises: e4cf6b0f8590
Create Date: 2026-09-03 01:25:45.001819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f4b5daff4'
down_revision: Union[str, Sequence[str], None] = 'e4cf6b0f8590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history_state', sa.Column('last_seed_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_history_state', sa.Column('last_seed_attempt_result', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history_state', 'last_seed_attempt_result')
    op.drop_column('chat_history_state', 'last_seed_attempt_at')
    # ### end Alembic commands ###
