"""almacenamiento en google drive: segmentos, trabajos y claves

Revision ID: c7c9f6d75957
Revises: e628c9f290d0
Create Date: 2026-09-03 13:48:06.589282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c9f6d75957'
down_revision: Union[str, Sequence[str], None] = 'e628c9f290d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('folder_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'path', name='uq_drive_folders_user_path')
    )
    op.create_table('google_drive_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('root_folder_id', sa.String(length=128), nullable=False),
    sa.Column('manifest_file_id', sa.String(length=128), nullable=True),
    sa.Column('bytes_uploaded', sa.BigInteger(), nullable=False),
    sa.Column('files_uploaded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_storage_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('storage_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('message_segment','media')", name='ck_storage_jobs_type'),
    sa.CheckConstraint("status IN ('pending','processing','complete','failed','paused')", name='ck_storage_jobs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'entity_id', name='uq_storage_jobs_entity')
    )
    op.create_index('ix_storage_jobs_listos', 'storage_jobs', ['status', 'next_retry_at'], unique=False)
    op.create_index('ix_storage_jobs_user', 'storage_jobs', ['user_id', 'status'], unique=False)
    op.create_table('message_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_jid', sa.String(length=128), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=True),
    sa.Column('first_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('last_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('uncompressed_bytes', sa.BigInteger(), nullable=False),
    sa.Column('compressed_bytes', sa.BigInteger(), nullable=False),
    sa.Column('stored_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('ciphertext_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('format_version', sa.Integer(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('building','uploading','ready','failed')", name='ck_message_segments_status'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'sequence_number', name='uq_message_segments_chat_seq')
    )
    op.create_index('ix_message_segments_chat', 'message_segments', ['chat_id', 'sequence_number'], unique=False)
    op.create_index('ix_message_segments_status', 'message_segments', ['status'], unique=False)
    op.create_index('ix_message_segments_user', 'message_segments', ['user_id'], unique=False)
    op.add_column('media_files', sa.Column('drive_file_id', sa.String(length=128), nullable=True))
    op.add_column('media_files', sa.Column('storage_status', sa.String(length=16), nullable=False,
              # Las filas anteriores a Drive no se han subido nunca:
              # 'local' es lo que de verdad les pasa, no un relleno.
              server_default='local'))
    op.add_column('media_files', sa.Column('stored_bytes', sa.BigInteger(), nullable=True))
    op.add_column('media_files', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('media_files', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('segment_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('segment_index', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('storage_status', sa.String(length=16), nullable=False,
              # Las filas anteriores a Drive no se han subido nunca:
              # 'local' es lo que de verdad les pasa, no un relleno.
              server_default='local'))
    op.add_column('messages', sa.Column('text_truncated', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_messages_segment_id'), 'messages', ['segment_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'message_segments', ['segment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_segment_id'), table_name='messages')
    op.drop_column('messages', 'text_truncated')
    op.drop_column('messages', 'storage_status')
    op.drop_column('messages', 'segment_index')
    op.drop_column('messages', 'segment_id')
    op.drop_column('media_files', 'last_accessed_at')
    op.drop_column('media_files', 'uploaded_at')
    op.drop_column('media_files', 'stored_bytes')
    op.drop_column('media_files', 'storage_status')
    op.drop_column('media_files', 'drive_file_id')
    op.drop_index('ix_message_segments_user', table_name='message_segments')
    op.drop_index('ix_message_segments_status', table_name='message_segments')
    op.drop_index('ix_message_segments_chat', table_name='message_segments')
    op.drop_table('message_segments')
    op.drop_index('ix_storage_jobs_user', table_name='storage_jobs')
    op.drop_index('ix_storage_jobs_listos', table_name='storage_jobs')
    op.drop_table('storage_jobs')
    op.drop_table('user_storage_keys')
    op.drop_table('google_drive_storage')
    op.drop_table('drive_folders')
    # ### end Alembic commands ###
