"""anclas de historial y blobs escaneados

Revision ID: e85126395c4a
Revises: b4af75317b72
Create Date: 2026-09-03 18:15:27.835582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85126395c4a'
down_revision: Union[str, Sequence[str], None] = 'b4af75317b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned_blobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=True),
    sa.Column('seeds_found', sa.BigInteger(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_account_id', 'sha256', name='uq_scanned_blobs_account_sha')
    )
    op.create_table('history_seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_jid', sa.String(length=128), nullable=False),
    sa.Column('wa_msg_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('from_me', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_account_id', 'chat_id', 'wa_msg_id', name='uq_history_seeds_chat_msg')
    )
    op.create_index('ix_history_seeds_chat', 'history_seeds', ['chat_id', 'timestamp'], unique=False)
    op.create_index('ix_history_seeds_user', 'history_seeds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_seeds_user', table_name='history_seeds')
    op.drop_index('ix_history_seeds_chat', table_name='history_seeds')
    op.drop_table('history_seeds')
    op.drop_table('scanned_blobs')
    # ### end Alembic commands ###
